import { StyleSheet } from 'react-native';
import { Colors } from '@/theme/colors';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.bgPink,
  },

  dotBackground: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    zIndex: 0,
  },
  dotRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 7,
  },
  dot: {
    width: 3, height: 3, borderRadius: 1.5,
    backgroundColor: Colors.pinkDot,
  },

  statsHeader: {
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
    paddingHorizontal: 12,
    height: 60,
    zIndex: 1,
  },
  statsLeft: {
    flexDirection: 'row',
    gap: 8,
  },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.white,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 6,
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  statIcon: { fontSize: 14 },
  settingsBtn: {
    width: 36, height: 36, borderRadius: 18,
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 4,
    elevation: 3,
  },
  settingsIcon: { fontSize: 16 },

  bannerHeader: {
    backgroundColor: Colors.pink,
    borderBottomWidth: 0,
    borderRadius: 20,
    marginHorizontal: 16,
    marginBottom: 14,
    height: 66,
    zIndex: 1,
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  bannerTitle: {
    color: Colors.white,
    fontSize: 18,
    fontWeight: 'bold',
    letterSpacing: 2,
    textShadowColor: 'rgba(200,0,80,0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  petCircle: {
    width: 48, height: 48, borderRadius: 24,
    backgroundColor: Colors.pinkSoft,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2.5,
    borderColor: Colors.white,
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 4,
  },
  petEmoji: { fontSize: 26 },

  subtitle: { marginBottom: 14, zIndex: 1, letterSpacing: 0.3 },

  scroll: { flex: 1, zIndex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 36,
    gap: 20,
  },

  card: {
    borderRadius: 22,
    borderWidth: 2,
    overflow: 'hidden',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    elevation: 6,
  },

  cardTopBand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 18,
    paddingHorizontal: 16,
  },
  sparkle1: {
    position: 'absolute',
    top: 8, right: 14,
    fontSize: 10,
    color: 'rgba(0,0,0,0.15)',
  },
  sparkle2: {
    position: 'absolute',
    top: 20, right: 34,
    fontSize: 7,
    color: 'rgba(0,0,0,0.1)',
  },
  sparkle3: {
    position: 'absolute',
    bottom: 8, right: 60,
    fontSize: 8,
    color: 'rgba(0,0,0,0.1)',
  },
  playBtn: {
    width: 48, height: 48, borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  playIcon: { width: 20, height: 20 },
  cardTitleGroup: { flex: 1, gap: 2 },
  cardName: { letterSpacing: 1.5 },
  lockedOverlay: {
    position: 'absolute',
    top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(255,255,255,0.45)',
  },

  cardBottom: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },

  starRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  star: { fontSize: 18 },
  starFilled: { color: Colors.starYellow },
  starEmpty: { color: 'rgba(255,255,255,0.45)' },
  starLabel: { marginLeft: 6 },

  badgePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  badgeEmoji: { width: 16, height: 16 },

  rewardCard: {
    marginHorizontal: 16,
    marginBottom: 16,
    backgroundColor: Colors.white,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: Colors.pinkMid,
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
    zIndex: 1,
  },
  rewardPetWrap: {
    width: 64, height: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rewardPetBlur: {
    width: 64, height: 64, borderRadius: 32,
    backgroundColor: Colors.pinkSoft,
    alignItems: 'center',
    justifyContent: 'center',
    opacity: 0.6,
  },
  rewardPetEmoji: { fontSize: 30 },
  rewardPetQ: {
    position: 'absolute',
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: Colors.pink,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Colors.pink,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 3,
  },
  rewardPetQText: {
    fontSize: 16, color: Colors.white, fontWeight: 'bold',
  },
  rewardBody: { flex: 1, gap: 4 },
  rewardSub: { opacity: 0.75, marginBottom: 2 },
  rewardProgressBg: {
    height: 8, borderRadius: 4,
    backgroundColor: Colors.pinkSoft,
    overflow: 'hidden',
  },
  rewardProgressFill: {
    height: 8, borderRadius: 4,
    backgroundColor: Colors.pink,
  },

  petPreviewWrap: {
    width: 40, height: 40, borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    marginLeft: 'auto',
  },
  petPreviewEmoji: { fontSize: 20 },
  petPreviewImg: { width: 24, height: 24 },

  petRewardRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: 'rgba(0,0,0,0.12)',
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  petRewardImg: { width: 18, height: 18 },
  petRewardLabel: { fontSize: 11 },

  dividerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 20,
    marginTop: 4,
    marginBottom: 12,
    zIndex: 1,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: Colors.pinkMid,
  },
  dividerDot: {
    fontSize: 10,
    color: Colors.pink,
    marginHorizontal: 8,
  },

  petAvatarOuter: {
    width: 52, height: 52, borderRadius: 26,
    backgroundColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.7)',
  },
  petAvatarInner: {
    width: 42, height: 42, borderRadius: 21,
    backgroundColor: Colors.pinkSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  petAvatarEmoji: { width: 32, height: 32 },

  cardDecorCircle: {},
  cardDecorCircleSmall: {},
  cardBody: {},
  cardRight: {},
  progressRow: {},
  progressTrack: {},
  progressFill: {},
  progressBarFill: {},
  stateCircle: {},
  stateIcon: {},
  badge: {},
  accent: {},
  bearWrap: {},
  bearEarL: {},
  bearEarR: {},
  bearFace: {},
  bearEyes: {},
  bearEye: {},
  bearSnout: {},
  bearNose: {},
  lockOverlay: {},
  shine: {},
});
